### ISSUE TITLE
Overhaul Tracking

### ISSUE THREAD

**Issue by erichte-ibm** [open-power/secvarctl#41]
There is a lot of work needed for the guest secure boot support. This work will be done in the `guest-devel` branch. All other branches appear to be obsolete and should be deleted after this work is merged.

Current known items needed to be fixed:
 - [ ] rewrite build system
 - [ ] re-implement cmake build (for packaging, mostly)
 - [ ] reformat entire tree in accordance to style guide
 - [ ] reorganize source directories in a more sensible way
 - [ ] remove excessive prints to `stdout`
 - [ ] reconcile crypto backend differences with libstb-secvar
   - [ ] move probably all crypto code into libstb-secvar
 - [ ] re-enable and improve CI
 - [ ] rework tests probably

**Comment by erichte-ibm** [comment]
Copy-pasting outstanding items from PR #42 

- [ ]     libstb secvar only supports openssl
- [ ]     move all crypto files into libstb-secvar
- [ ]     backend specific builds fail (this support should be dropped)
- [ ]     `crypto_write_only` is uselless and should be removed
- [ ]     review the common/ directory
- [ ]     fix various memcmp with strlen uses
- [ ]     `make memcheck` is failing due to memory leaks
